script that compiles a C file but does not link.

diff --git a/0x00-hello_world/1-compiler b/0x00-hello_world/1-compiler
--- a/0x00-hello_world/1-compiler
+++ b/0x00-hello_world/1-compiler
@@ -1,7 +1,10 @@
 #!/bin/bash
-
-# Get the filename from the environment variable CFILE
 filename="$CFILE"
-
-# Compile the C file without linking, outputting to a .o file with the same name
 gcc -c "$filename"
+if [ $? -eq 0 ]; then
+    echo "Compilation successful."
+else
+    echo "Compilation failed."
+    exit 1
+fi
+
